apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  creationTimestamp: null
  description: ConfigMap as Service
  name: configmap-promise-template
  tags:
    - kratix
    - configmap-promise
  title: ConfigMap
spec:
  lifecycle: experimental
  owner: kratix-platform
  parameters:
    - properties:
        name:
          description: The name of the configmap
          errorMessage:
            pattern: must be lowercase letters, numbers, and hyphens; must start and end with a letter or number.
          maxLength: 63
          minLength: 1
          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
          title: Name
          type: string
      required:
        - name
      title: Metadata
    - properties:
        data:
          ui:title: ConfigMap Contents
          additionalProperties:
            type: string
          description: The Data of the ConfigMap
          type: object
      title: Config Data
  steps:
    - action: ske:configure-resource
      id: ske-configure-resource
      input:
        manifest: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            labels:
              backstage.io/kubernetes-id: namespace
              kratix.io/managed-by: backstage
            name: ${{ parameters.name }}
            namespace: default
          data: ${{ parameters.data | dump }}
      name: Configure ConfigMap
  type: kratix-resource
